### ISSUE TITLE
Web page with documentation not updated anymore

### ISSUE THREAD

**Issue by nyoxi** [oVirt/ovirt-engine-sdk#22] opened 2020-01-28 12:49 UTC
The Python documentation is not automatically updated for some time. It's been dead since 4.2 or some time around that. Could this be fixed?

**Comment by sandrobonazzola** [comment] 2020-01-28 13:06
@mwperina @machacekondra can you please have a look?

**Comment by mwperina** [comment] 2020-01-29 09:03
Ori is already working on that

**Comment by mwperina** [comment] 2020-01-30 07:49
@oliel

**Comment by oliel** [comment] 2020-01-30 12:14
I believe that master branch is documented correctly since:
  https://gerrit.ovirt.org/#/c/106020/
was merged. 

I've asserted this by searching for the documentation of a relatively recent change: 

(from CHANGES.adoc):

  == 4.3.0 / Jan 16 2018
New features:
* Add `activate` input param to add/install/approve host

As can be seen, 'activate' parameter exists in the documentation for these actions, e.g:

http://ovirt.github.io/ovirt-engine-sdk/master/services.m.html#ovirtsdk4.services.HostService.approve

So the problem is (not anymore) the frozen documentation process, but rather missing documentation for 4.2, 4.3 and 4.4 versions. I'm working on it

**Comment by nyoxi** [comment] 2020-01-30 12:30
I have to disagree. :) E.g. I don't see `CLUSTER_DEFAULT` in `BiosType`: http://ovirt.github.io/ovirt-engine-sdk/master/types.m.html#ovirtsdk4.types.BiosType

Or I don't see `MDevType`, or `use_ignition` argument in `VmService.start()`: http://ovirt.github.io/ovirt-engine-sdk/master/services.m.html#ovirtsdk4.services.VmService.start

**Comment by oliel** [comment] 2020-01-30 12:34
Got it, taking a look.

**Comment by oliel** [comment] 2020-02-03 09:02
Ok, I stand corrected, now the master branch is ok following this patch: 

  https://gerrit.ovirt.org/#/c/106714/

See CLUSTER_DEFAULT here: 
 http://ovirt.github.io/ovirt-engine-sdk/master/types.m.html#ovirtsdk4.types.BiosType

**Comment by sandrobonazzola** [comment] 2020-05-14 20:27
Closing based on above comment.

**Closed by sandrobonazzola** 2020-05-14 20:27 UTC
